export const PlayersBattersNameMapped = {
    'AK Markram': { index: 0, country: 'South Africa' },
    'H Klaasen': { index: 1, country: 'South Africa' },
    'Q de Kock': { index: 2, country: 'South Africa' },
    'T Bavuma': { index: 3, country: 'South Africa' },
    'M Labuschagne': { index: 4, country: 'Australia' },
    'GJ Maxwell': { index: 5, country: 'Australia' },
    'R Ravindra': { index: 6, country: 'New Zealand' },
    'GD Phillips': { index: 7, country: 'New Zealand' },
    'Shubman Gill': { index: 8, country: 'India' },
    'SS Iyer': { index: 9, country: 'India' },
    'JM Bairstow': { index: 10, country: 'England' },
    'BA Stokes': { index: 11, country: 'England' },
    'JC Buttler': { index: 12, country: 'England' },
    'RG Sharma': { index: 13, country: 'India' },
    'DA Warner': { index: 14, country: 'Australia' },
    'KL Rahul': { index: 15, country: 'India' },
    'SPD Smith': { index: 16, country: 'Australia' },
    'KS Williamson': { index: 17, country: 'New Zealand' },
    'V Kohli': { index: 18, country: 'India' },
};


export const PlayersBowlerNameMapped = {
    'AU Rashid': { index: 0, country: 'England' },
    'R Ashwin': { index: 1, country: 'India' },
    'TA Boult': { index: 2, country: 'New Zealand' },
    'JJ Bumrah': { index: 3, country: 'India' },
    'PJ Cummins': { index: 4, country: 'Australia' },
    'JR Hazlewood': { index: 5, country: 'Australia' },
    'MJ Henry': { index: 6, country: 'New Zealand' },
    'Kuldeep Yadav': { index: 7, country: 'India' },
    'NM Lyon': { index: 8, country: 'Australia' },
    'Mohammad Nabi': { index: 9, country: 'Afghanistan' },
    'K Rabada': { index: 10, country: 'South Africa' },
    'Shakib Al Hasan': { index: 11, country: 'Bangladesh' },
    'Mohammed Shami': { index: 12, country: 'India' },
    'TG Southee': { index: 13, country: 'New Zealand' },
    'MA Starc': { index: 14, country: 'Australia' },
};

export const BattersName = [
    'AK Markram', 'H Klaasen', 'Q de Kock', 'T Bavuma', 'M Labuschagne',
    'GJ Maxwell', 'R Ravindra', 'GD Phillips', 'Shubman Gill', 'SS Iyer',
    'JM Bairstow', 'BA Stokes', 'JC Buttler', 'RG Sharma', 'DA Warner',
    'KL Rahul', 'SPD Smith', 'KS Williamson', 'V Kohli',
];

export const BowlersName = [
    'AU Rashid', 'R Ashwin', 'TA Boult', 'JJ Bumrah', 'PJ Cummins',
    'JR Hazlewood', 'MJ Henry', 'Kuldeep Yadav', 'NM Lyon', 'Mohammad Nabi',
    'K Rabada', 'Shakib Al Hasan', 'Mohammed Shami', 'TG Southee', 'MA Starc',
];

export const Ground = [
    'Potchefstroom',
    'Bloemfontein',
    'East London',
    'Gqeberha',
    'Cape Town',
    'Centurion',
    'Johannesburg',
    'Durban',
    'Galle',
    'Colombo (SSC)',
    'Dambulla',
    'Colombo (RPS)',
    'Kimberley',
    'Paarl',
    'Perth',
    'Adelaide',
    'Hobart',
    'The Oval',
    'Southampton',
    'Cardiff',
    'Birmingham',
    'Lord\'s',
    'Chester-le-Street',
    'Manchester',
    'Visakhapatnam',
    'Pune',
    'Karachi',
    'Rawalpindi',
];

export const Country = [
    'Bangladesh',
    'Zimbabwe',
    'India',
    'Australia',
    'Sri Lanka',
    'Pakistan',
    'England',
    'West Indies',
    'Afghanistan',
    'New Zealand',
    'Ireland',
    'Netherlands',
    'U.A.E.',
    'South Africa',
    'Scotland',
    'Namibia',
    'Nepal',
    'Hong Kong',
    'Kenya',
    'Canada'
  ];
  

  export const RunRange={
    0: {'min':0, 'max':30},
    1: {'min':30, 'max':60},
    2: {'min':60, 'max':100},
    3: {'min':100, 'max':150},
    4: {'min':150, 'max':200},
    5: {'min':200, 'max':'+'},
  }

  export const countryIndexing = {
    'Bangladesh': 0,
    'Zimbabwe': 1,
    'India': 2,
    'Australia': 3,
    'Sri Lanka': 4,
    'Pakistan': 5,
    'England': 6,
    'West Indies': 7,
    'Afghanistan': 8,
    'New Zealand': 9,
    'Ireland': 10,
    'Netherlands': 11,
    'U.A.E.': 12,
    'South Africa': 13,
    'Scotland': 14,
    'Namibia': 15,
    'Nepal': 16,
    'Hong Kong': 17,
    'Kenya': 18,
    'Canada': 19,
  };

  export const conditionIndexing = {
    'Clear': 0,
    'Partially cloudy': 1,
    'Rain, Partially cloudy': 2,
    'Rain, Overcast': 3,
    'Overcast': 4,
    'Rain': 5,
    'Snow, Partially cloudy': 6,
    'Snow, Rain, Overcast': 7,
    'Snow, Rain, Partially cloudy': 8,
    'Rain, Fog': 9,
    'Snow, Overcast': 10,
  };

  export const groundIndexing = {
    'Potchefstroom': 0,
    'Bloemfontein': 1,
    'East London': 2,
    'Gqeberha': 3,
    'Cape Town': 4,
    'Centurion': 5,
    'Johannesburg': 6,
    'Durban': 7,
    'Galle': 8,
    'Colombo (SSC)': 9,
    'Dambulla': 10,
    'Colombo (RPS)': 11,
    'Kimberley': 12,
    'Paarl': 13,
    'Perth': 14,
    'Adelaide': 15,
    'Hobart': 16,
    'The Oval': 17,
    'Southampton': 18,
    'Cardiff': 19,
    'Birmingham': 20,
    "Lord's": 21,
    'Chester-le-Street': 22,
    'Manchester': 23,
    'Visakhapatnam': 24,
    'Pune': 25,
    'Karachi': 26,
    'Rawalpindi': 27,
    'Gros Islet': 28,
    "St George's": 29,
    'Dublin (Malahide)': 30,
    'Belfast': 31,
    'Abu Dhabi': 32,
    'Dubai (DSC)': 33,
    'Sharjah': 34,
    'Christchurch': 35,
    'Leeds': 36,
    'Bristol': 37,
    'Thiruvananthapuram': 38,
    'Guwahati': 39,
    'Indore': 40,
    'Lucknow': 41,
    'Ranchi': 42,
    'Delhi': 43,
    'Sydney': 44,
    'Benoni': 45,
    'Dharamsala': 46,
    'Wankhede': 47,
    'Chennai': 48,
    'Eden Gardens': 49,
    'Pallekele': 50,
    'Carrara': 51,
    'Lahore': 52,
    'Cuttack': 53,
    'Rajkot': 54,
    'Bengaluru': 55,
    'Hambantota': 56,
    'Chattogram': 57,
    'Mirpur': 58,
    'Harare': 59,
    'Bulawayo': 60,
    'Mount Maunganui': 61,
    'Hamilton': 62,
    'Melbourne': 63,
    'Canberra': 64,
    'Auckland': 65,
    'Wellington': 66,
    'Kanpur': 67,
    'Nagpur': 68,
    'Providence': 69,
    'Basseterre': 70,
    'Bridgetown': 71,
    'Dunedin': 72,
    'Nottingham': 73,
    'Mohali': 74,
    'Brisbane': 75,
    'Cairns': 76,
    'Ahmedabad': 77,
    'Hyderabad': 78,
    'Jaipur': 79,
    'Tolerance Oval': 80,
    'Taunton': 81,
    'Townsville': 82,
    'Queenstown': 83,
    'Nelson': 84,
    'Napier': 85,
    'Edinburgh': 86,
    'The Hague': 87,
    'Kingston': 88,
    'Raipur': 89,
    'Port of Spain': 90,
    'Roseau': 91,
    'Tarouba': 92,
    'Lauderhill': 93,
    'North Sound': 94,
    'Dublin': 95,
    'Multan': 96,
    'Aberdeen': 97,
    'Amstelveen': 98,
    'Brabourne': 99,
    'Kochi': 100,
    'Fatullah': 101,
    'Colombo (PSS)': 102,
    'Kingstown': 103,
    'Vadodara': 104,
    'Whangarei': 105,
    'Gwalior': 106,
  };

  export const formatIndexing = {
    'Test': 0,
    'ODI': 1,
    'T20I': 2,
  };

